name: activ_education
description: Plateforme d'orientation scolaire et professionnelle - Togo
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.7.0

  # Local storage (token JWT)
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2

  # Image picker
  image_picker: ^1.1.2

  # File picker
  file_picker: ^8.0.0

  # WebSocket
  web_socket_channel: ^3.0.1

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Voice assistant
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.1

  # Charts
  fl_chart: ^0.69.2

  # Utils
  intl: ^0.19.0
  flutter_dotenv: ^6.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  assets:
    - .env
    - assets/images/
    # - assets/icons/
    # - assets/animations/
