-- =====================================================================
-- Schéma Supabase : table etablissements_togo
-- Source : seed/Etablissements.html (Google Sheet exporté, 97 établissements, 19 colonnes)
-- À exécuter dans Supabase > SQL Editor (ou via psql)
-- =====================================================================

create table if not exists public.etablissements_togo (
  id                    bigint generated by default as identity primary key,
  id_etablissement      text unique not null,             -- ex: 'TG-UL-001'
  nom_officiel          text not null,                    -- ex: 'Université de Lomé'
  sigle                 text,                             -- ex: 'UL'
  logo_url              text,                             -- URL du logo (souvent 'Non disponible')
  devise                text,
  slogan                text,
  type                  text,                             -- 'Université publique', 'École privée', etc.
  statut_juridique      text,
  numero_agrement       text,                             -- référence décret/arrêté
  date_agrement         date,                             -- ISO 8601 (AAAA-MM-JJ)
  autorite_tutelle      text,
  accreditations        text,
  reconnaissance_cames  text,                             -- 'Oui' / 'Non' / détails
  annee_creation        integer,                          -- ex: 1970
  historique            text,
  presentation          text,
  mission               text,
  vision                text,
  valeurs               text,
  inserted_at           timestamptz not null default now()
);

-- Index utiles
create index if not exists idx_etablissements_sigle on public.etablissements_togo (sigle);
create index if not exists idx_etablissements_type on public.etablissements_togo (type);
create index if not exists idx_etablissements_annee on public.etablissements_togo (annee_creation);

-- Recherche plein texte FR (nom + présentation)
create index if not exists idx_etablissements_fts
  on public.etablissements_togo
  using gin (to_tsvector('simple',
    coalesce(nom_officiel,'') || ' ' || coalesce(sigle,'') || ' ' || coalesce(presentation,'')
  ));

-- RLS : lecture publique, écriture uniquement via service_role (script Python)
alter table public.etablissements_togo enable row level security;

drop policy if exists "etablissements read public" on public.etablissements_togo;
create policy "etablissements read public"
  on public.etablissements_togo for select
  using (true);

-- Pas de policy INSERT/UPDATE/DELETE -> seul service_role bypass RLS
comment on table public.etablissements_togo is
  'Etablissements supérieurs du Togo (97) — import depuis seed/Etablissements.html (Google Sheet)';
